version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:834342613816:task-definition/aws-hello-world-rest:1"
        LoadBalancerInfo:
          ContainerName: "aws-hello-world-rest-api-container"
          ContainerPort: "80"
        PlatformVersion: "LATEST"
